### ISSUE TITLE
پی لاین یا زرین پال

### ISSUE THREAD

**Issue by iMohammadd** [rezakho/payment#1]
سلام
فک کنم اشتباهی واسه کلاس پی لاین زرین پال رو تعریف کردی

**Comment by rezakho** [comment]
<p dir=rtl>
این پروژه تکمیل نشده و آماده نیست و تست بود، خیلی از موارد رو اصلاح کردم و هنوز بروز نشده!
<br/>
مشکل اصلی پیدا کردن کوتاه ترین و تمیزترین  API بود که تقریبا حل شده و به زودی بروز میشه
تشکر
</p>
